image:
  train_export:
    repository: ljh415/resnet_training
    tag: v0.0.24
  triton:
    repository: nvcr.io/nvidia/tritonserver
    tag: 23.04-py3
  grpc_client:
    repository: ljh415/grpc_client
    tag: v0.0.11

storage:
  pvcName: shared-storage-pvc
  size: 10Gi
  accessMode: ReadWriteMany
  storage:ClassName: standard

resources:
  train:
    env:
      epochs: "1"
      batchSize: "64"
      lr: "0.001"
      savePath: "/storage"
    requests:
      cpu: "4"
      memory: "8Gi"
    limits:
      cpu: "6"
      memory: "16Gi"
  export:
    env:
      savePath: "/storage"
      exportType: "onnx"
    requests:
      cpu: "0.5"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "8Gi"
  triton:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
  grpc_client:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"

triton:
  model_repo_path: /storage/models
  http_port: 8000
  grpc_port: 8001
  metrics_port: 8002
