apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: training-container
        image: ljh415/resnet_training:v0.0.22
        imagePullPolicy: IfNotPresent
        command: ["python", "train.py"]
        env:
          - name: EPOCHS
            value: "10"
          - name: BATCH_SIZE
            value: "64"
          - name: LR
            value: "0.001"
          - name: SAVE_PATH
            value: "/storage"
        resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "8"
              memory: "16Gi"
        volumeMounts:
          - mountPath: "/storage"
            name: shared-storage
      restartPolicy: Never
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-storage-pvc