apiVersion: v1
kind: Service
metadata:
  name: triton-service
spec:
  type: NodePort
  selector:
    app: triton-inference
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http-rest
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: grpc
    - protocol: TCP
      port: 8002
      targetPort: 8002
      name: metrics
